name: 'IPFS Deploy'
description: 'Deploys code & content to IPFS pinning service'
inputs: # TODO: Add support for more pinning services & DNS
  pinning-service:
    description: 'The pinning service to use'
    required: true
    default: 'pinata'
  pinata-api-key:
    description: 'API key for Piñata pinning service'
    required: false
  pinata-secret-api-key:
    description: 'Secret API key for Piñata pinning service'
    required: false
runs:
  using: 'node12'
  main: 'bin/github-action.js'
branding:
  icon: 'box'
  color: 'blue'